# Generated by Django 2.1.3 on 2018-11-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mascota',
            options={'permissions': (('puede_agregar', 'agrega mascotas'),)},
        ),
    ]
