"""
Django settings for misperris project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7j!q7z*0-81gz)z2et--xyhw1*q@ba4yltk-7i@-mg&@fs(gn$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

#Le decimos a Django donde se redigira el usuario una vez autenticado correctamente
LOGIN_REDIRECT_URL = "/" 

#Le decimos a Django donde se redigira el usuario cuando haya cerrado la sesion
LOGOUT_REDIRECT_URL = "/accounts/login"




# Application definition

SOCIAL_AUTH_FACEBOOK_KEY = '707775829596784' #App ID
SOCIAL_AUTH_FACEBOOK_SECRET = '8a5fe6e970269b8cd96d97d53d67e099' #App Secret

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig', #CoreConfig es una clase que se encuentra en apps y se pone aqui para
    #cambiarle el nombre a un titulo de algo de Django, solo para que se entienda mejor
    'accounts', #Estamos cargando la aplicacion Accounts para el login
    'social_django', #Esto es para usar con facebook
    'crispy_forms', #Es para usar el plugin de Boostrap y colocarselo automaticamente a los formularios  
    'api',
    'pwa',
    'fcm_django',
]

#Ahora le decimos al plugin crispy con que libreria el trabajará
CRISPY_TEMPLATE_PACK = 'boostrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'misperris.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates/')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'misperris.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR , "media")
MEDIA_URL = '/media/'

AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

#Estos 2 lineas se ponen para que el usuario no tenga que ver errores que no tiene porque ver
SOCIAL_AUTH_LOGIN_ERROR_URL = '/'
SOCIAL_AUTH_RAISE_EXCEPTIONS = False

#Le diremos a Django donde queda nuestro serviceworker
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'serviceworker.js') 

PWA_APP_NAME = "MisPerris"

PWA_APP_ICONS = [
    {
        'src':'static/core/img/logoAplicacion.png',
        'sizes':'160x160'
    }
]

FCM_DJANGO_SETTINGS = {
        "FCM_SERVER_KEY": "AAAAKmTv70M:APA91bH591BXGaGUrW4v6zxqvrSx63rArVj93q-2fYm3BI7oR5_9xZGVkLM71MiBwz90hNALah5FCwspdg9jWv5kgw-GniWa0Z0Jw6sO_5aZ_IN51WqNLESCTJ28AOrk-bT0QipTotlB",
         # true if you want to have only one active device per registered user at a time
         # default: False
        "ONE_DEVICE_PER_USER": False,
         # devices to which notifications cannot be sent,
         # are deleted upon receiving error response from FCM
         # default: False
        "DELETE_INACTIVE_DEVICES": False,
}
